### ISSUE TITLE
TypeError: array_validator() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by khw11044** [mbodiai/embodied-agents#103] opened 2024-11-18 09:49 UTC
I encountered the following errors while running the provided notebooks:

'Record_Dataset_using_embodied_agents_(SimplerENV)_v1_1.ipynb' and 'Mbodi_Example_Simple_Robot_Agent.ipynb', which were shared by the MbodiAI team.

### 1. Error in 
Record_Dataset_using_embodied_agents_(SimplerENV)_v1_1.ipynb:

The error occurs in the following code block:
```
robot = SimplerENVRobot()
robot.init_recorder()
with robot.record("pick up the coke can"):
    for instruction in instructions:
        print("[INSTRUCTION]:", instruction)
        # Get response from the language agent based on the instruction and image
        action = agent.act_and_parse(instruction, robot.capture(), SimpleRobotControl)
        # Execute the actions with the SimplerEnv Interface
        robot.do(action)

```
### 2. Error in 
Mbodi_Example_Simple_Robot_Agent.ipynb:

The error occurs in the following code block:
```
observation_space = spaces.Dict({
    'image': Image(size=(224, 224)).space(),
    'instruction': spaces.Text(1000)
})
action_space = AnswerAndActionsList(actions=[HandControl()] * 6).space()
recorder = Recorder('example_recorder',
                    out_dir='saved_datasets',
                    observation_space=observation_space,
                    action_space=action_space)

```

What should I do to resolve these issues?
Thank you

**Comment by khw11044** [comment] 2024-11-18 10:09
First of all, I'm honored that you answered my question. Thank you so much.
Currently this code also throws the same error. 

```
from mbodied.agents.motion.openvla_agent import OpenVlaAgent
from mbodied.robots import SimRobot


def main() -> None:
    # Use the remote gradio server as the agent actor.
    motor_agent = OpenVlaAgent(model_src="https://api.mbodi.ai/community-models/")

    # Subclass Robot and implement the do() method for your specific hardware.
    robot = SimRobot()

    # Use the same instruction throughout."pick up the coke can")
    instruction = input("Your instruction: example) Pick up the remote: \n")

    while True:
        # Image can be initialized with most image types, including file paths.
        hand_control = motor_agent.act(instruction, robot.capture())
        robot.do(hand_control)


if __name__ == "__main__":
    main()
```

The error message is as follows:

```
(mbodied) (base) khw@khw:~/res/OpenVLA/Colab$ /home/khw/anaconda3/envs/mbodied/bin/python /home/khw/res/OpenVLA/Colab/00.test.py
Loaded as API: https://api.mbodi.ai/community-models/ ✔
Your instruction: example) Pick up the remote: 
Pick up the remote
╭───────────────────────────── Traceback (most recent call last) ──────────────────────────────╮
│ /home/khw/res/OpenVLA/Colab/00.test.py:22 in <module>                                        │
│                                                                                              │
│   19                                                                                         │
│   20                                                                                         │
│   21 if __name__ == "__main__":                                                              │
│ ❱ 22 │   main()                                                                              │
│   23                                                                                         │
│                                                                                              │
│ /home/khw/res/OpenVLA/Colab/00.test.py:17 in main                                            │
│                                                                                              │
│   14 │                                                                                       │
│   15 │   while True:                                                                         │
│   16 │   │   # Image can be initialized with most image types, including file paths.         │
│ ❱ 17 │   │   hand_control = motor_agent.act(instruction, robot.capture())                    │
│   18 │   │   robot.do(hand_control)                                                          │
│   19                                                                                         │
│   20                                                                                         │
│                                                                                              │
│ /home/khw/anaconda3/envs/mbodied/lib/python3.10/site-packages/mbodied/robots/sim_robot.py:73 │
│ in capture                                                                                   │
│                                                                                              │
│   70 │   def capture(self, **_) -> Image:                                                    │
│   71 │   │   """Captures an image."""                                                        │
│   72 │   │   resource = Path("resources") / "xarm.jpeg"                                      │
│ ❱ 73 │   │   return Image(resource, size=(224, 224))                                         │
│   74 │                                                                                       │
│   75 │   def get_observation(self) -> Image:                                                 │
│   76 │   │   """Alias of capture for recording."""                                           │
│                                                                                              │
│ /home/khw/anaconda3/envs/mbodied/lib/python3.10/site-packages/mbodied/types/sense/vision.py: │
│ 177 in __init__                                                                              │
│                                                                                              │
│   174 │   │   │   │   kwargs["pil"] = pil                                                    │
│   175 │   │   │   elif bytes_obj is not None:                                                │
│   176 │   │   │   │   kwargs["bytes"] = bytes_obj                                            │
│ ❱ 177 │   │   super().__init__(**kwargs)                                                     │
│   178 │                                                                                      │
│   179 │   def __repr__(self):                                                                │
│   180 │   │   """Return a string representation of the image."""                             │
│                                                                                              │
│ /home/khw/anaconda3/envs/mbodied/lib/python3.10/site-packages/mbodied/types/sample.py:93 in  │
│ __init__                                                                                     │
│                                                                                              │
│    90 │   │   │   │   data.update(datum)                                                     │
│    91 │   │   │   else:                                                                      │
│    92 │   │   │   │   data["datum"] = datum                                                  │
│ ❱  93 │   │   super().__init__(**data)                                                       │
│    94 │                                                                                      │
│    95 │   def __hash__(self) -> int:                                                         │
│    96 │   │   """Return a hash of the Sample instance."""                                    │
│                                                                                              │
│ /home/khw/anaconda3/envs/mbodied/lib/python3.10/site-packages/pydantic/main.py:212 in        │
│ __init__                                                                                     │
│                                                                                              │
│    209 │   │   """                                                                           │
│    210 │   │   # `__tracebackhide__` tells pytest and some other tools to omit this function │
│        from tracebacks                                                                       │
│    211 │   │   __tracebackhide__ = True                                                      │
│ ❱  212 │   │   validated_self = self.__pydantic_validator__.validate_python(data,            │
│        self_instance=self)                                                                   │
│    213 │   │   if self is not validated_self:                                                │
│    214 │   │   │   warnings.warn(                                                            │
│    215 │   │   │   │   'A custom validator is returning a value other than `self`.\n'        │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: array_validator() got an unexpected keyword argument 'labels'
```

**Comment by khw11044** [comment] 2024-11-18 10:17
I ran the following code in the file **Record_Dataset_using_embodied_agents_(SimplerENV)_v1_1.ipynb:**

```
# Some example instructions.
instructions = [
    "Move left by 0.3",
    "Move left a bit more",
    "Move down",
    "Move down a lot",
]
robot = SimplerENVRobot()
robot.init_recorder()
with robot.record("pick up the coke can"):
  for instruction in instructions:
      print("[INSTRUCTION]:", instruction)
      # Get response from the language agent based on the instruction and image
      action = agent.act_and_parse(instruction, robot.capture(), SimpleRobotControl)
      # Execute the actions with the SimplerEnv Interface
      robot.do(action)

```

However, the following error occurred:

```
# Some example instructions.
instructions = [
    "Move left by 0.3",
    "Move left a bit more",
    "Move down",
    "Move down a lot",
]
robot = SimplerENVRobot()
robot.init_recorder()
with robot.record("pick up the coke can"):
  for instruction in instructions:
      print("[INSTRUCTION]:", instruction)
      # Get response from the language agent based on the instruction and image
      action = agent.act_and_parse(instruction, robot.capture(), SimpleRobotControl)
      # Execute the actions with the SimplerEnv Interface
      robot.do(action)
```

Thank you for your time.

**Comment by Zaid-Waghoo** [comment] 2024-11-19 17:05
Hey, thanks for pointing out the issue. 
It was due to the python version, in certain cases pydantic validation fails with python version 3.10. 

The issue is now fixed in the PyPi version as well as in the main branch of the repository. It should now work with  python 3.10, 3.11 and 3.12. 

Closing this issue now, let us know if you face any issues or have any questions. Thanks

**Closed by Zaid-Waghoo** 2024-11-19 17:05 UTC
